apiVersion: v1
kind: Service
metadata:
  name: shopping-rabbitmq
  labels:
    type: shopping-rabbitmq-service
    app: shopping
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    type: rabbitmq-pod
    app: shopping
