apiVersion: v1
kind: Service
metadata:
  name: shopping-redis
  labels:
    type: shopping-redis-service
    app: shopping
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    type: redis-pod
    app: shopping
