apiVersion: v1
kind: Service
metadata:
  name: shopping-celery-flower
  labels:
    type: shopping-celery-flower-service
    app: shopping
spec:
  type: LoadBalancer
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    type: celery-flower-pod
    app: shopping
