apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  labels:
    type: shopping-api-service
    app: shopping
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    type: api-pod
    app: shopping
